//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _307Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class C307_Software
    {
        public byte SoftwareID { get; set; }
        public string OperatingSystem { get; set; }
        public string Version { get; set; }
        public string Manufacturer { get; set; }
    }
}
